version: '3'

services:
  dev:
    container_name: restful-api
    image: restful-api
    ports:
      - 3000:8000
    # volumes:
    #   - . :/app
    env_file:   
      - ./.env 
    environment:
      PORT: 8000
      DATABASE_DEV: ${DOCKER_DB_URL}
    command: sh -c "npm run db:ready && npm run dev" 
    depends_on: 
      - db
      - cache
             
  db:
    image: postgres
    ports:
      - 5432:5432
    env_file: 
      - ./.env
    environment: 
      POSTGRES_USER: ${DOCKER_DB_USER}
      POSTGRES_PASSWORD: ${DOCKER_DB_PASS}
      POSTGRES_DB: ${DOCKER_DB}
      
  cache:
    image: redis
    ports: 
      - 6379:6379
    env_file: 
      - ./.env
    environment: 
      REDIS_URL: ${REDIS_URL}    